src/kernel.h: Fix missing <sys/time.h> header
Fix issues with missing <sys/time.h> header that resulted in

 In file included from ../../git/src/priv.h:17,
                  from ../../git/src/liberio-mmap.c:17:
 ../../git/src/kernel.h:65:18: error: field 'timestamp' has incomplete type
   struct timeval  timestamp;

when built with musl libc.

Signed-off-by: Moritz Fischer <moritz.fischer@ettus.com>